version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - keamanan_jaringan
    volumes:
      - keamanan_jaringan:/var/lib/mysql

  webserver:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./php.setup.Dockerfile
    volumes:
      - ./src/:/var/www/html
    networks:
      - keamanan_jaringan
    working_dir: /var/www/html
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./src/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - keamanan_jaringan

volumes:
  keamanan_jaringan:


networks:
  keamanan_jaringan:
